// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/contest/createContest": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "Contest"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "name": "duration",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "note",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "problemsJson",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "rule",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "startTime",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "title",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.CreateContestResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/contest/getContestList": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "Contest"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "name": "length",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "startIndex",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.GetContestListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/contest/getContestSubmissionList": {
            "get": {
                "tags": [
                    "Contest"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "name": "cid",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.GetContestSubmissionListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/contest/getStandingsByRank": {
            "get": {
                "tags": [
                    "Contest"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "name": "cid",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "len",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "startIdx",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.GetStandingsByRankResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/contest/register": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "Contest"
                ],
                "parameters": [
                    {
                        "description": "注册比赛",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.RegisterContestRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.RegisterContestResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/contest/unregister": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "Contest"
                ],
                "parameters": [
                    {
                        "description": "取消注册比赛",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UnregisterContestRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.UnregisterContestResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/contest/{cid}": {
            "get": {
                "tags": [
                    "Contest"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "contest ID",
                        "name": "cid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.GetContestResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/index": {
            "get": {
                "responses": {}
            }
        },
        "/problem/createProblem": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "Problem"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "name": "description",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "inputFormat",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "name": "memoryLimit",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "outputFormat",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "tagsJson",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "testSamplesJson",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "name": "timeLimit",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "title",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.CreateProblemResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/problem/getProblemList": {
            "get": {
                "tags": [
                    "Problem"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "name": "length",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "startIndex",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.GetProblemListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/problem/getTags": {
            "get": {
                "tags": [
                    "Problem"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.GetTagsResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/problem/{pid}": {
            "get": {
                "tags": [
                    "Problem"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "problem ID",
                        "name": "pid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.GetProblemResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/submission/getSubmissionList": {
            "get": {
                "tags": [
                    "Submission"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "name": "pid",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "uid",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.GetSubmissionListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/submit": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "Submit"
                ],
                "parameters": [
                    {
                        "description": "提交代码",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.SubmitRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.SubmitResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/changePassword": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "User"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "name": "newPassword",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "password",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.ChangePasswordResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "tags": [
                    "User"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "name": "password",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "username",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.LoginResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/register": {
            "post": {
                "tags": [
                    "User"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "name": "password",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "username",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.RegisterResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "contest.Contest": {
            "type": "object",
            "properties": {
                "cid": {
                    "type": "string"
                },
                "duration": {
                    "$ref": "#/definitions/time.Duration"
                },
                "note": {
                    "type": "string"
                },
                "problems": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/contest.ContestProblem"
                    }
                },
                "registered": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "rule": {
                    "type": "string"
                },
                "startTime": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/contest.ContestStatus"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "contest.ContestProblem": {
            "type": "object",
            "properties": {
                "nick": {
                    "type": "string"
                },
                "pid": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "contest.ContestStatus": {
            "type": "string",
            "enum": [
                "Register",
                "Running",
                "Close"
            ],
            "x-enum-varnames": [
                "REGISTER",
                "RUNNING",
                "CLOSE"
            ]
        },
        "contest.ProblemSolveStatus": {
            "type": "object",
            "properties": {
                "failCnt": {
                    "type": "integer"
                },
                "nick": {
                    "type": "string"
                },
                "penalty": {
                    "type": "integer"
                },
                "pid": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/model.StatusSet"
                }
            }
        },
        "contest.RankListData": {
            "type": "object",
            "properties": {
                "pss": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/contest.ProblemSolveStatus"
                    }
                },
                "uid": {
                    "type": "string"
                }
            }
        },
        "model.LangSet": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3
            ],
            "x-enum-comments": {
                "CPP": "\"Cpp\"",
                "GO": "\"Go\"",
                "JAVA": "\"Java\"",
                "PYTHON": "\"Python\""
            },
            "x-enum-varnames": [
                "CPP",
                "JAVA",
                "PYTHON",
                "GO"
            ]
        },
        "model.Problem": {
            "type": "object",
            "properties": {
                "dataRange": {
                    "description": "options",
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "inputFormat": {
                    "type": "string"
                },
                "memoryLimit": {
                    "type": "integer"
                },
                "outputFormat": {
                    "type": "string"
                },
                "pid": {
                    "type": "string"
                },
                "point": {
                    "type": "integer"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "testSamples": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.TestCase"
                    }
                },
                "timeLimit": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "tutorial": {
                    "type": "string"
                }
            }
        },
        "model.StatusSet": {
            "type": "string",
            "enum": [
                "UnSubmit",
                "UnAccept",
                "Pending",
                "Compiling",
                "Judging",
                "Compile Error",
                "Accept",
                "Wrong Answer",
                "Time Limit Exceeded",
                "Memory Limit Exceeded",
                "Runtime Error",
                "Output Limit Exceeded",
                "Unknown Error"
            ],
            "x-enum-varnames": [
                "UNSUBMIT",
                "UNACCEPT",
                "PENDING",
                "COMPILING",
                "JUDGING",
                "CE",
                "AC",
                "WA",
                "TLE",
                "MLE",
                "RE",
                "OLE",
                "UKE"
            ]
        },
        "model.Submission": {
            "type": "object",
            "properties": {
                "cid": {
                    "type": "string"
                },
                "executeMemory": {
                    "type": "integer"
                },
                "executeTime": {
                    "type": "integer"
                },
                "lang": {
                    "$ref": "#/definitions/model.LangSet"
                },
                "pid": {
                    "type": "string"
                },
                "point": {
                    "description": "options",
                    "type": "integer"
                },
                "runningMemory": {
                    "type": "integer"
                },
                "runningTime": {
                    "type": "integer"
                },
                "sid": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/model.StatusSet"
                },
                "submitCode": {
                    "type": "string"
                },
                "submitTime": {
                    "type": "string"
                },
                "uid": {
                    "type": "integer"
                }
            }
        },
        "model.TestCase": {
            "type": "object",
            "properties": {
                "explanation": {
                    "type": "string"
                },
                "input": {
                    "type": "string"
                },
                "note": {
                    "type": "string"
                },
                "output": {
                    "type": "string"
                }
            }
        },
        "request.RegisterContestRequest": {
            "type": "object",
            "properties": {
                "cid": {
                    "type": "string"
                }
            }
        },
        "request.SubmitRequest": {
            "type": "object",
            "properties": {
                "cid": {
                    "type": "string"
                },
                "lang": {
                    "type": "integer"
                },
                "pid": {
                    "type": "string"
                },
                "submitCode": {
                    "type": "string"
                },
                "submitTime": {
                    "type": "string"
                }
            }
        },
        "request.UnregisterContestRequest": {
            "type": "object",
            "properties": {
                "cid": {
                    "type": "string"
                }
            }
        },
        "response.ChangePasswordResponse": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string"
                }
            }
        },
        "response.CreateContestResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.CreateProblemResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.GetContestListResponse": {
            "type": "object",
            "properties": {
                "contests": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.SimpleContest"
                    }
                }
            }
        },
        "response.GetContestResponse": {
            "type": "object",
            "properties": {
                "contest": {
                    "$ref": "#/definitions/contest.Contest"
                }
            }
        },
        "response.GetContestSubmissionListResponse": {
            "type": "object",
            "properties": {
                "submissions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Submission"
                    }
                }
            }
        },
        "response.GetProblemListResponse": {
            "type": "object",
            "properties": {
                "problems": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.SimpleProblem"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "response.GetProblemResponse": {
            "type": "object",
            "properties": {
                "problem": {
                    "$ref": "#/definitions/model.Problem"
                }
            }
        },
        "response.GetStandingsByRankResponse": {
            "type": "object",
            "properties": {
                "rankList": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/contest.RankListData"
                    }
                },
                "rule": {
                    "type": "string"
                },
                "usernameList": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "response.GetSubmissionListResponse": {
            "type": "object",
            "properties": {
                "submissions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Submission"
                    }
                }
            }
        },
        "response.GetTagsResponse": {
            "type": "object",
            "properties": {
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "response.LoginResponse": {
            "type": "object",
            "properties": {
                "admin": {
                    "type": "integer"
                },
                "token": {
                    "type": "string"
                },
                "uid": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "response.RegisterContestResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.RegisterResponse": {
            "type": "object",
            "properties": {
                "username": {
                    "type": "string"
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        },
        "response.SimpleContest": {
            "type": "object",
            "properties": {
                "cid": {
                    "type": "string"
                },
                "duration": {
                    "$ref": "#/definitions/time.Duration"
                },
                "isRegistered": {
                    "type": "boolean"
                },
                "note": {
                    "type": "string"
                },
                "startTime": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/contest.ContestStatus"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "response.SimpleProblem": {
            "type": "object",
            "properties": {
                "memoryLimit": {
                    "type": "integer"
                },
                "pid": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "timeLimit": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "response.SubmitResponse": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string"
                }
            }
        },
        "response.UnregisterContestResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "time.Duration": {
            "type": "integer",
            "enum": [
                -9223372036854775808,
                9223372036854775807,
                1,
                1000,
                1000000,
                1000000000,
                60000000000,
                3600000000000
            ],
            "x-enum-varnames": [
                "minDuration",
                "maxDuration",
                "Nanosecond",
                "Microsecond",
                "Millisecond",
                "Second",
                "Minute",
                "Hour"
            ]
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
