definitions:
  contest.Contest:
    properties:
      cid:
        type: string
      duration:
        $ref: '#/definitions/time.Duration'
      note:
        type: string
      problems:
        items:
          $ref: '#/definitions/contest.ContestProblem'
        type: array
      registered:
        items:
          type: integer
        type: array
      rule:
        type: string
      startTime:
        type: string
      status:
        $ref: '#/definitions/contest.ContestStatus'
      title:
        type: string
    type: object
  contest.ContestProblem:
    properties:
      nick:
        type: string
      pid:
        type: string
      title:
        type: string
    type: object
  contest.ContestStatus:
    enum:
    - Register
    - Running
    - Close
    type: string
    x-enum-varnames:
    - REGISTER
    - RUNNING
    - CLOSE
  contest.ProblemSolveStatus:
    properties:
      failCnt:
        type: integer
      nick:
        type: string
      penalty:
        type: integer
      pid:
        type: string
      status:
        $ref: '#/definitions/model.StatusSet'
    type: object
  contest.RankListData:
    properties:
      pss:
        items:
          $ref: '#/definitions/contest.ProblemSolveStatus'
        type: array
      uid:
        type: string
    type: object
  model.LangSet:
    enum:
    - 0
    - 1
    - 2
    - 3
    type: integer
    x-enum-comments:
      CPP: '"Cpp"'
      GO: '"Go"'
      JAVA: '"Java"'
      PYTHON: '"Python"'
    x-enum-varnames:
    - CPP
    - JAVA
    - PYTHON
    - GO
  model.Problem:
    properties:
      dataRange:
        description: options
        type: string
      description:
        type: string
      inputFormat:
        type: string
      memoryLimit:
        type: integer
      outputFormat:
        type: string
      pid:
        type: string
      point:
        type: integer
      tags:
        items:
          type: string
        type: array
      testSamples:
        items:
          $ref: '#/definitions/model.TestCase'
        type: array
      timeLimit:
        type: integer
      title:
        type: string
      tutorial:
        type: string
    type: object
  model.StatusSet:
    enum:
    - UnSubmit
    - UnAccept
    - Pending
    - Compiling
    - Judging
    - Compile Error
    - Accept
    - Wrong Answer
    - Time Limit Exceeded
    - Memory Limit Exceeded
    - Runtime Error
    - Output Limit Exceeded
    - Unknown Error
    type: string
    x-enum-varnames:
    - UNSUBMIT
    - UNACCEPT
    - PENDING
    - COMPILING
    - JUDGING
    - CE
    - AC
    - WA
    - TLE
    - MLE
    - RE
    - OLE
    - UKE
  model.Submission:
    properties:
      cid:
        type: string
      executeMemory:
        type: integer
      executeTime:
        type: integer
      lang:
        $ref: '#/definitions/model.LangSet'
      pid:
        type: string
      point:
        description: options
        type: integer
      runningMemory:
        type: integer
      runningTime:
        type: integer
      sid:
        type: string
      status:
        $ref: '#/definitions/model.StatusSet'
      submitCode:
        type: string
      submitTime:
        type: string
      uid:
        type: integer
    type: object
  model.TestCase:
    properties:
      explanation:
        type: string
      input:
        type: string
      note:
        type: string
      output:
        type: string
    type: object
  request.RegisterContestRequest:
    properties:
      cid:
        type: string
    type: object
  request.SubmitRequest:
    properties:
      cid:
        type: string
      lang:
        type: integer
      pid:
        type: string
      submitCode:
        type: string
      submitTime:
        type: string
    type: object
  request.UnregisterContestRequest:
    properties:
      cid:
        type: string
    type: object
  response.ChangePasswordResponse:
    properties:
      msg:
        type: string
    type: object
  response.CreateContestResponse:
    properties:
      message:
        type: string
      success:
        type: boolean
    type: object
  response.CreateProblemResponse:
    properties:
      message:
        type: string
      success:
        type: boolean
    type: object
  response.GetContestListResponse:
    properties:
      contests:
        items:
          $ref: '#/definitions/response.SimpleContest'
        type: array
    type: object
  response.GetContestResponse:
    properties:
      contest:
        $ref: '#/definitions/contest.Contest'
    type: object
  response.GetContestSubmissionListResponse:
    properties:
      submissions:
        items:
          $ref: '#/definitions/model.Submission'
        type: array
    type: object
  response.GetProblemListResponse:
    properties:
      problems:
        items:
          $ref: '#/definitions/response.SimpleProblem'
        type: array
      total:
        type: integer
    type: object
  response.GetProblemResponse:
    properties:
      problem:
        $ref: '#/definitions/model.Problem'
    type: object
  response.GetStandingsByRankResponse:
    properties:
      rankList:
        items:
          $ref: '#/definitions/contest.RankListData'
        type: array
      rule:
        type: string
      usernameList:
        items:
          type: string
        type: array
    type: object
  response.GetSubmissionListResponse:
    properties:
      submissions:
        items:
          $ref: '#/definitions/model.Submission'
        type: array
    type: object
  response.GetTagsResponse:
    properties:
      tags:
        items:
          type: string
        type: array
    type: object
  response.LoginResponse:
    properties:
      admin:
        type: integer
      token:
        type: string
      uid:
        type: integer
      username:
        type: string
    type: object
  response.RegisterContestResponse:
    properties:
      message:
        type: string
      success:
        type: boolean
    type: object
  response.RegisterResponse:
    properties:
      username:
        type: string
    type: object
  response.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  response.SimpleContest:
    properties:
      cid:
        type: string
      duration:
        $ref: '#/definitions/time.Duration'
      isRegistered:
        type: boolean
      note:
        type: string
      startTime:
        type: string
      status:
        $ref: '#/definitions/contest.ContestStatus'
      title:
        type: string
    type: object
  response.SimpleProblem:
    properties:
      memoryLimit:
        type: integer
      pid:
        type: string
      tags:
        items:
          type: string
        type: array
      timeLimit:
        type: integer
      title:
        type: string
    type: object
  response.SubmitResponse:
    properties:
      msg:
        type: string
    type: object
  response.UnregisterContestResponse:
    properties:
      message:
        type: string
      success:
        type: boolean
    type: object
  time.Duration:
    enum:
    - -9223372036854775808
    - 9223372036854775807
    - 1
    - 1000
    - 1000000
    - 1000000000
    - 60000000000
    - 3600000000000
    type: integer
    x-enum-varnames:
    - minDuration
    - maxDuration
    - Nanosecond
    - Microsecond
    - Millisecond
    - Second
    - Minute
    - Hour
info:
  contact: {}
paths:
  /contest/{cid}:
    get:
      parameters:
      - description: contest ID
        in: path
        name: cid
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.GetContestResponse'
              type: object
      tags:
      - Contest
  /contest/createContest:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - in: formData
        name: duration
        type: integer
      - in: formData
        name: note
        type: string
      - in: formData
        name: problemsJson
        type: string
      - in: formData
        name: rule
        type: string
      - in: formData
        name: startTime
        type: string
      - in: formData
        name: title
        type: string
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.CreateContestResponse'
              type: object
      security:
      - ApiKeyAuth: []
      tags:
      - Contest
  /contest/getContestList:
    get:
      parameters:
      - in: query
        name: length
        type: integer
      - in: query
        name: startIndex
        type: integer
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.GetContestListResponse'
              type: object
      security:
      - ApiKeyAuth: []
      tags:
      - Contest
  /contest/getContestSubmissionList:
    get:
      parameters:
      - in: query
        name: cid
        type: string
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.GetContestSubmissionListResponse'
              type: object
      tags:
      - Contest
  /contest/getStandingsByRank:
    get:
      parameters:
      - in: query
        name: cid
        type: string
      - in: query
        name: len
        type: integer
      - in: query
        name: startIdx
        type: integer
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.GetStandingsByRankResponse'
              type: object
      tags:
      - Contest
  /contest/register:
    post:
      parameters:
      - description: 注册比赛
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.RegisterContestRequest'
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.RegisterContestResponse'
              type: object
      security:
      - ApiKeyAuth: []
      tags:
      - Contest
  /contest/unregister:
    post:
      parameters:
      - description: 取消注册比赛
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.UnregisterContestRequest'
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.UnregisterContestResponse'
              type: object
      security:
      - ApiKeyAuth: []
      tags:
      - Contest
  /index:
    get:
      responses: {}
  /problem/{pid}:
    get:
      parameters:
      - description: problem ID
        in: path
        name: pid
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.GetProblemResponse'
              type: object
      tags:
      - Problem
  /problem/createProblem:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - in: formData
        name: description
        type: string
      - in: formData
        name: inputFormat
        type: string
      - in: formData
        name: memoryLimit
        type: integer
      - in: formData
        name: outputFormat
        type: string
      - in: formData
        name: tagsJson
        type: string
      - in: formData
        name: testSamplesJson
        type: string
      - in: formData
        name: timeLimit
        type: integer
      - in: formData
        name: title
        type: string
      - description: 文件
        in: formData
        name: file
        required: true
        type: file
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.CreateProblemResponse'
              type: object
      security:
      - ApiKeyAuth: []
      tags:
      - Problem
  /problem/getProblemList:
    get:
      parameters:
      - in: query
        name: length
        type: integer
      - in: query
        name: startIndex
        type: integer
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.GetProblemListResponse'
              type: object
      tags:
      - Problem
  /problem/getTags:
    get:
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.GetTagsResponse'
              type: object
      tags:
      - Problem
  /submission/getSubmissionList:
    get:
      parameters:
      - in: query
        name: pid
        type: string
      - in: query
        name: uid
        type: integer
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.GetSubmissionListResponse'
              type: object
      tags:
      - Submission
  /submit:
    post:
      parameters:
      - description: 提交代码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.SubmitRequest'
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.SubmitResponse'
              type: object
      security:
      - ApiKeyAuth: []
      tags:
      - Submit
  /user/changePassword:
    post:
      parameters:
      - in: formData
        name: newPassword
        type: string
      - in: formData
        name: password
        type: string
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.ChangePasswordResponse'
              type: object
      security:
      - ApiKeyAuth: []
      tags:
      - User
  /user/login:
    post:
      parameters:
      - in: formData
        name: password
        type: string
      - in: formData
        name: username
        type: string
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.LoginResponse'
              type: object
      tags:
      - User
  /user/register:
    post:
      parameters:
      - in: formData
        name: password
        type: string
      - in: formData
        name: username
        type: string
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.RegisterResponse'
              type: object
      tags:
      - User
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
