definitions:
  model.LangSet:
    enum:
    - 0
    - 1
    - 2
    - 3
    type: integer
    x-enum-comments:
      CPP: '"Cpp"'
      GO: '"Go"'
      JAVA: '"Java"'
      PYTHON: '"Python"'
    x-enum-varnames:
    - CPP
    - JAVA
    - PYTHON
    - GO
  model.Problem:
    properties:
      dataRange:
        description: options
        type: string
      description:
        type: string
      memoryLimit:
        type: integer
      pid:
        type: string
      point:
        type: integer
      tags:
        items:
          type: string
        type: array
      testSamples:
        items:
          $ref: '#/definitions/model.TestCase'
        type: array
      timeLimit:
        type: integer
      title:
        type: string
      tutorial:
        type: string
    type: object
  model.StatusSet:
    enum:
    - Pending
    - Compiling
    - Judging
    - Compile Error
    - Accept
    - Wrong Answer
    - Time Limit Exceeded
    - Memory Limit Exceeded
    - Runtime Error
    - Output Limit Exceeded
    - Unknown Error
    type: string
    x-enum-varnames:
    - PENDING
    - COMPILING
    - JUDGING
    - CE
    - AC
    - WA
    - TLE
    - MLE
    - RE
    - OLE
    - UKE
  model.Submission:
    properties:
      lang:
        $ref: '#/definitions/model.LangSet'
      pid:
        type: string
      point:
        description: options
        type: integer
      runningMemory:
        type: integer
      runningTime:
        type: integer
      sid:
        type: string
      status:
        $ref: '#/definitions/model.StatusSet'
      submitCode:
        type: string
      submitTime:
        type: string
      uid:
        type: integer
    type: object
  model.TestCase:
    properties:
      explanation:
        type: string
      input:
        type: string
      note:
        type: string
      output:
        type: string
    type: object
  request.SubmitRequest:
    properties:
      lang:
        type: integer
      pid:
        type: string
      submitCode:
        type: string
      submitTime:
        type: string
    type: object
  response.ChangePasswordResponse:
    properties:
      msg:
        type: string
    type: object
  response.CreateProblemResponse:
    properties:
      message:
        type: string
      success:
        type: boolean
    type: object
  response.GetProblemListResponse:
    properties:
      problems:
        items:
          $ref: '#/definitions/response.SimpleProblem'
        type: array
    type: object
  response.GetProblemResponse:
    properties:
      problem:
        $ref: '#/definitions/model.Problem'
    type: object
  response.GetSubmissionListResponse:
    properties:
      submissions:
        items:
          $ref: '#/definitions/model.Submission'
        type: array
    type: object
  response.LoginResponse:
    properties:
      admin:
        type: integer
      token:
        type: string
      uid:
        type: integer
      username:
        type: string
    type: object
  response.RegisterResponse:
    properties:
      username:
        type: string
    type: object
  response.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  response.SimpleProblem:
    properties:
      pid:
        type: string
      title:
        type: string
    type: object
  response.SubmitResponse:
    properties:
      msg:
        type: string
    type: object
info:
  contact: {}
paths:
  /index:
    get:
      responses: {}
  /problem/{pid}:
    get:
      parameters:
      - description: problem ID
        in: path
        name: pid
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.GetProblemResponse'
              type: object
      tags:
      - Problem
  /problem/createProblem:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - in: formData
        name: description
        type: string
      - in: formData
        name: memoryLimit
        type: integer
      - in: formData
        name: testSamplesJson
        type: string
      - in: formData
        name: timeLimit
        type: integer
      - in: formData
        name: title
        type: string
      - description: 文件
        in: formData
        name: file
        required: true
        type: file
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.CreateProblemResponse'
              type: object
      security:
      - ApiKeyAuth: []
      tags:
      - Problem
  /problem/getProblemList:
    get:
      parameters:
      - in: query
        name: length
        type: integer
      - in: query
        name: startIndex
        type: integer
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.GetProblemListResponse'
              type: object
      tags:
      - Problem
  /submission/getSubmissionList:
    get:
      parameters:
      - in: query
        name: pid
        type: string
      - in: query
        name: uid
        type: integer
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.GetSubmissionListResponse'
              type: object
      tags:
      - Submission
  /submit:
    post:
      parameters:
      - description: 提交代码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.SubmitRequest'
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.SubmitResponse'
              type: object
      security:
      - ApiKeyAuth: []
      tags:
      - Submit
  /user/changePassword:
    post:
      parameters:
      - in: formData
        name: newPassword
        type: string
      - in: formData
        name: password
        type: string
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.ChangePasswordResponse'
              type: object
      security:
      - ApiKeyAuth: []
      tags:
      - User
  /user/login:
    post:
      parameters:
      - in: formData
        name: password
        type: string
      - in: formData
        name: username
        type: string
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.LoginResponse'
              type: object
      tags:
      - User
  /user/register:
    post:
      parameters:
      - in: formData
        name: password
        type: string
      - in: formData
        name: username
        type: string
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.RegisterResponse'
              type: object
      tags:
      - User
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
